extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: true
swap:
  Graphql: GraphQL
  graphql: GraphQL
  NextJS: Next.js
  Typescript: TypeScript
  Javascript: JavaScript
  Postgres: PostgreSQL
