artifact_uri: /Users/pratik_n/Desktop/MyComputer/Sentifargo/runs/mlflow/716084780746542089/73e8fe0669bb404cab7e52a64edaf242/artifacts
end_time: 1765996124151
entry_point_name: ''
experiment_id: '716084780746542089'
lifecycle_stage: active
run_id: 73e8fe0669bb404cab7e52a64edaf242
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1765996111440
status: 3
tags: []
user_id: pratik_n
