artifact_uri: /Users/pratik_n/Desktop/MyComputer/universal-anomaly-intelligence-v2/runs/mlflow/716084780746542089/e9e1263a26004adf8cd01c59b75d9140/artifacts
end_time: null
entry_point_name: ''
experiment_id: '716084780746542089'
lifecycle_stage: active
run_id: e9e1263a26004adf8cd01c59b75d9140
run_name: brand_quick
source_name: ''
source_type: 4
source_version: ''
start_time: 1765996368972
status: 1
tags: []
user_id: pratik_n
