"""
Training script for Brand/Logo Detection using YOLOv8.

Usage:
    python -m src.train.train_brand_logo_detector
"""
import os
import sys
from pathlib import Path
from ultralytics import YOLO

def main():
    # 1. Setup paths
    # Default dataset yaml generated by scripts/prepare_brand_data.py
    # If --kind was used in preparation, update this path accordingly.
    data_yaml = Path("data/processed/brand_yolo/brands.yaml")
    
    if not data_yaml.exists():
        # Fallback check for 'logo' kind
        data_yaml_logo = Path("data/processed/brand_yolo/logo/brands.yaml")
        if data_yaml_logo.exists():
            data_yaml = data_yaml_logo
        else:
            print(f"Error: Dataset config not found at {data_yaml}")
            print("Please run: python scripts/prepare_brand_data.py")
            sys.exit(1)

    # 2. Config
    model_name = os.getenv("BRAND_YOLO_MODEL", "yolov8n.pt")
    epochs = int(os.getenv("BRAND_EPOCHS", "5"))
    imgsz = int(os.getenv("BRAND_IMGSZ", "640"))
    batch = int(os.getenv("BRAND_BATCH", "16"))
    
    print(f"Starting training with model={model_name} epochs={epochs} imgsz={imgsz} batch={batch}")
    
    # 3. Train
    # We use project='runs/detect' and name='train' with exist_ok=True
    # to ensure the output is always at runs/detect/train/weights/best.pt
    # which matches the fallback path in src/vision/brand/recognizer.py
    model = YOLO(model_name)
    results = model.train(
        data=str(data_yaml.resolve()),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project="runs/detect",
        name="train",
        exist_ok=True,
        pretrained=True,
        verbose=True
    )
    
    print("\nTraining complete.")
    print(f"Best model saved to: {results.best}")
    print("You can now use this model with the fallback path in src/vision/brand/recognizer.py")

if __name__ == "__main__":
    main()