artifact_location: /Users/pratik_n/Desktop/MyComputer/Sentifargo/runs/mlflow/690575434915126183
creation_time: 1765999741509
experiment_id: '690575434915126183'
last_update_time: 1765999741509
lifecycle_stage: active
name: /Users/pratik_n/Desktop/MyComputer/Sentifargo/runs/detect
