/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/chat": {
    /** Chat */
    post: operations["chat_api_chat_post"];
  };
  "/api/chat/multimodal": {
    /**
     * Chat Multimodal
     * @description Single request: optional audio/image/video + message -> routed response + meta.
     *
     * This endpoint runs in-process inference for voice/vision and attaches results to `meta`.
     */
    post: operations["chat_multimodal_api_chat_multimodal_post"];
  };
  "/api/chat/stream": {
    /**
     * Chat Stream
     * @description SSE-style streaming endpoint.
     *
     * If OPENAI_API_KEY is set, streams LLM tokens from OpenAI.
     * Otherwise, falls back to word-chunk streaming of orchestrator reply.
     */
    get: operations["chat_stream_api_chat_stream_get"];
  };
  "/api/rag/query": {
    /**
     * Rag Query
     * @description Return top passages from local docs (data/docs).
     */
    post: operations["rag_query_api_rag_query_post"];
  };
  "/api/recommend": {
    /** Recommend */
    post: operations["recommend_api_recommend_post"];
  };
  "/api/recommend/explain": {
    /** Explain */
    post: operations["explain_api_recommend_explain_post"];
  };
  "/api/recommend/multimodal": {
    /**
     * Recommend Multimodal
     * @description CLIP + FAISS multimodal recommender (additive).
     *
     * Provide either a text query, an uploaded image, or image_url/image_base64. If the index isn't built yet,
     * this endpoint returns 503 with instructions.
     */
    post: operations["recommend_multimodal_api_recommend_multimodal_post"];
  };
  "/api/recommend/clothes": {
    /**
     * Recommend Clothes
     * @description Image/text clothing recommendations (offline-first).
     *
     * Uses CLIP image tags when available; falls back to text-only matching.
     */
    post: operations["recommend_clothes_api_recommend_clothes_post"];
  };
  "/api/recommend/topn": {
    /** Recommend Topn */
    post: operations["recommend_topn_api_recommend_topn_post"];
  };
  "/api/behavior": {
    /** Predict Behavior */
    post: operations["predict_behavior_api_behavior_post"];
  };
  "/api/behavior/logs": {
    /**
     * Predict Behavior Logs
     * @description Upload a behavior log CSV and return per-user anomaly scores (best-effort).
     */
    post: operations["predict_behavior_logs_api_behavior_logs_post"];
  };
  "/api/fraud": {
    /**
     * Predict Fraud
     * @description Predict fraud probability for a transaction.
     *
     * This endpoint:
     * 1. Loads the fraud model (if not already loaded)
     * 2. Prepares input features in the correct format
     * 3. Runs model inference
     * 4. Returns fraud probability score
     *
     * Args:
     *     req: FraudRequest containing list of feature values
     *
     * Returns:
     *     dict: {
     *         "score": float,           # Fraud probability 0.0 to 1.0
     *         "input_features": int,    # Number of features provided
     *         "expected_features": int, # Number model expects
     *         "feature_names": list     # Names of features (if known)
     *     }
     *
     * Raises:
     *     HTTPException 503: If model is not available
     *     HTTPException 500: If inference fails
     *
     * Example usage with curl:
     *     curl -X POST http://localhost:8000/api/fraud \
     *          -H "Content-Type: application/json" \
     *          -d '{"features": [0.5, -1.2, 3.4, 0.0, 1.8]}'
     */
    post: operations["predict_fraud_api_fraud_post"];
  };
  "/api/cyber": {
    /** Predict Cyber */
    post: operations["predict_cyber_api_cyber_post"];
  };
  "/api/vision/train": {
    /** Vision Experiment */
    post: operations["vision_experiment_api_vision_train_post"];
  };
  "/api/vision/predict": {
    /**
     * Vision Predict
     * @description Predict class label for an uploaded image or image_url using the trained ResNet artifact.
     */
    post: operations["vision_predict_api_vision_predict_post"];
  };
  "/api/vision/face_emotion/predict": {
    /**
     * Face Emotion Predict
     * @description Predict a 7-class facial emotion label from an uploaded image.
     */
    post: operations["face_emotion_predict_api_vision_face_emotion_predict_post"];
  };
  "/api/vision/video/predict": {
    /**
     * Vision Video Predict
     * @description Predict for an uploaded video by sampling frames, aggregating probabilities, and scoring temporal-consistency.
     *
     * If `models/vision/video_temporal_model.pkl` exists, also returns a learned temporal confidence score
     * via `temporal_confidence_model`.
     */
    post: operations["vision_video_predict_api_vision_video_predict_post"];
  };
  "/health": {
    /**
     * Health Check
     * @description Quick health check endpoint.
     */
    get: operations["health_check_health_get"];
  };
  "/health/live": {
    /**
     * Liveness Check
     * @description Kubernetes liveness probe.
     */
    get: operations["liveness_check_health_live_get"];
  };
  "/health/ready": {
    /**
     * Readiness Check
     * @description Kubernetes readiness probe with component checks.
     */
    get: operations["readiness_check_health_ready_get"];
  };
  "/health/detailed": {
    /**
     * Detailed Health Check
     * @description Detailed health check with all components.
     */
    get: operations["detailed_health_check_health_detailed_get"];
  };
  "/metrics": {
    /**
     * Prometheus Metrics
     * @description Prometheus metrics endpoint.
     */
    get: operations["prometheus_metrics_metrics_get"];
  };
  "/ready": {
    /**
     * Ready
     * @description Simple ready check for load balancers.
     */
    get: operations["ready_ready_get"];
  };
  "/api/risk/analyze": {
    /** Risk Analyze */
    post: operations["risk_analyze_api_risk_analyze_post"];
  };
  "/api/monitor/log": {
    /** Log Event */
    post: operations["log_event_api_monitor_log_post"];
  };
  "/api/monitor/summary": {
    /** Summary */
    get: operations["summary_api_monitor_summary_get"];
  };
  "/api/monitor/drift": {
    /** Drift */
    get: operations["drift_api_monitor_drift_get"];
  };
  "/api/monitor/risk_summary": {
    /** Risk Summary */
    get: operations["risk_summary_api_monitor_risk_summary_get"];
  };
  "/api/monitor/events": {
    /**
     * Events
     * @description Return last N raw monitoring events (demo/debug).
     *
     * kind:
     *   - "risk"  -> `data/monitoring/logs/risk_events.jsonl`
     *   - "fraud" -> `data/monitoring/logs/fraud_events.jsonl`
     */
    get: operations["events_api_monitor_events_get"];
  };
  "/api/monitor/baseline/build": {
    /** Build Baseline */
    post: operations["build_baseline_api_monitor_baseline_build_post"];
  };
  "/api/voice/emotion": {
    /** Voice Emotion */
    post: operations["voice_emotion_api_voice_emotion_post"];
  };
  "/api/rag/ingest": {
    /** Ingest Docs */
    post: operations["ingest_docs_api_rag_ingest_post"];
  };
  "/api/rag/upload": {
    /**
     * Upload Doc
     * @description Upload a .txt/.md doc into `data/docs/` and rebuild the local RAG index.
     */
    post: operations["upload_doc_api_rag_upload_post"];
  };
  "/api/dsa-rag/ask": {
    /** Ask */
    post: operations["ask_api_dsa_rag_ask_post"];
  };
  "/api/dsa-rag/ingest": {
    /** Ingest Docs */
    post: operations["ingest_docs_api_dsa_rag_ingest_post"];
  };
  "/api/dsa-rag/upload": {
    /** Upload Doc */
    post: operations["upload_doc_api_dsa_rag_upload_post"];
  };
  "/api/vision/brand/predict": {
    /**
     * Predict Brand
     * @description Predict brand logos from an uploaded image or remote payload.
     *
     * Returns a list of detections: {brand, confidence, bbox:[x1,y1,x2,y2]}.
     */
    post: operations["predict_brand_api_vision_brand_predict_post"];
  };
  "/api/stt/transcribe": {
    /** Transcribe Audio */
    post: operations["transcribe_audio_api_stt_transcribe_post"];
  };
  "/api/tts/speak": {
    /** Tts Speak */
    post: operations["tts_speak_api_tts_speak_post"];
  };
  "/api/vision/video_temporal/predict": {
    /** Predict */
    post: operations["predict_api_vision_video_temporal_predict_post"];
  };
  "/api/health": {
    /**
     * Api Health
     * @description Health check endpoint that returns system status and capabilities.
     *
     * Used by:
     * - Monitoring systems (Kubernetes, Docker health checks)
     * - Frontend to display system status
     * - DevOps to verify deployment
     *
     * Returns:
     *     dict: System status including:
     *         - status: "ok" if healthy
     *         - service: Service name
     *         - version: API version
     *         - python: Python version info
     *         - platform: OS information
     *         - optional_features: Available ML capabilities
     *
     * Example response:
     *     {
     *         "status": "ok",
     *         "service": "omnichatx",
     *         "version": "0.2",
     *         "python": {"version": "3.11.0", "implementation": "CPython"},
     *         "platform": {"system": "Darwin", "release": "23.0.0", "machine": "arm64"},
     *         "optional_features": {
     *             "webrtc": true,
     *             "stt": true,
     *             "clip": false,
     *             "faiss": true
     *         }
     *     }
     */
    get: operations["api_health_api_health_get"];
  };
  "/": {
    /**
     * Root Redirect
     * @description Root endpoint - Redirects to the UI or returns API info.
     *
     * Behavior:
     * - If UI is built: Redirects to /ui/ (React frontend)
     * - If UI not built: Returns a simple JSON message
     */
    get: operations["root_redirect__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AskRequest */
    AskRequest: {
      /** Query */
      query: string;
    };
    /** BaselineRequest */
    BaselineRequest: {
      /**
       * Events N
       * @default 2000
       */
      events_n?: number;
      /** Samples */
      samples?: {
          [key: string]: number;
        }[] | null;
    };
    /** BehaviorRequest */
    BehaviorRequest: {
      /** Features */
      features: number[];
    };
    /** Body_chat_multimodal_api_chat_multimodal_post */
    Body_chat_multimodal_api_chat_multimodal_post: {
      /**
       * Message
       * @default
       */
      message?: string;
      /**
       * Instruction
       * @default
       */
      instruction?: string;
      /**
       * User Id
       * @default anon
       */
      user_id?: string;
      /**
       * Use Rag
       * @default true
       */
      use_rag?: boolean;
      /** Audio */
      audio?: string | null;
      /** Image */
      image?: string | null;
      /** Video */
      video?: string | null;
      /** Document */
      document?: string | null;
      /**
       * Fps
       * @default 1
       */
      fps?: number;
      /**
       * Max Frames
       * @default 25
       */
      max_frames?: number;
      /**
       * Transcribe Audio
       * @default false
       */
      transcribe_audio?: boolean;
      /** Stt Language */
      stt_language?: string | null;
    };
    /** Body_face_emotion_predict_api_vision_face_emotion_predict_post */
    Body_face_emotion_predict_api_vision_face_emotion_predict_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_predict_api_vision_video_temporal_predict_post */
    Body_predict_api_vision_video_temporal_predict_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_predict_behavior_logs_api_behavior_logs_post */
    Body_predict_behavior_logs_api_behavior_logs_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_predict_brand_api_vision_brand_predict_post */
    Body_predict_brand_api_vision_brand_predict_post: {
      /** File */
      file?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Image Base64 */
      image_base64?: string | null;
    };
    /** Body_recommend_clothes_api_recommend_clothes_post */
    Body_recommend_clothes_api_recommend_clothes_post: {
      /** Text */
      text?: string | null;
      /**
       * Top K
       * @default 5
       */
      top_k?: number;
      /** Image */
      image?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Image Base64 */
      image_base64?: string | null;
    };
    /** Body_recommend_multimodal_api_recommend_multimodal_post */
    Body_recommend_multimodal_api_recommend_multimodal_post: {
      /** Text */
      text?: string | null;
      /**
       * Top K
       * @default 5
       */
      top_k?: number;
      /** Image */
      image?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Image Base64 */
      image_base64?: string | null;
    };
    /** Body_transcribe_audio_api_stt_transcribe_post */
    Body_transcribe_audio_api_stt_transcribe_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
      /** Language */
      language?: string | null;
    };
    /** Body_upload_doc_api_dsa_rag_upload_post */
    Body_upload_doc_api_dsa_rag_upload_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_upload_doc_api_rag_upload_post */
    Body_upload_doc_api_rag_upload_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_vision_predict_api_vision_predict_post */
    Body_vision_predict_api_vision_predict_post: {
      /** File */
      file?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Image Base64 */
      image_base64?: string | null;
    };
    /** Body_vision_video_predict_api_vision_video_predict_post */
    Body_vision_video_predict_api_vision_video_predict_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** Body_voice_emotion_api_voice_emotion_post */
    Body_voice_emotion_api_voice_emotion_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** ChatRequest */
    ChatRequest: {
      /** Message */
      message?: string | null;
      /** Text */
      text?: string | null;
      /**
       * User Id
       * @default anon
       */
      user_id?: string;
      /**
       * Use Rag
       * @default true
       */
      use_rag?: boolean;
    };
    /** CyberRequest */
    CyberRequest: {
      /** Features */
      features: number[];
    };
    /** DriftReport */
    DriftReport: {
      /** Window */
      window: string;
      /** Drift Score */
      drift_score: number;
      /** Per Feature */
      per_feature: {
        [key: string]: {
          [key: string]: number;
        };
      };
      /** Status */
      status: string;
      /** Generated At */
      generated_at?: string;
    };
    /** ExplainRequest */
    ExplainRequest: {
      /** User Id */
      user_id?: string | number | null;
      /** Item Id */
      item_id: string;
    };
    /** FraudLogEvent */
    FraudLogEvent: {
      /** Timestamp */
      timestamp: string;
      /** Request Id */
      request_id: string;
      /** User Id */
      user_id: string;
      /** Model Version */
      model_version: string;
      /** Features Summary */
      features_summary: Record<string, never>;
      /** Prediction Score */
      prediction_score: number;
      /** Prediction Label */
      prediction_label: string;
      /** Latency Ms */
      latency_ms: number;
    };
    /**
     * FraudRequest
     * @description Request body schema for fraud prediction.
     *
     * The 'features' field should contain numerical values representing
     * transaction characteristics. Common features include:
     * - Transaction amount (normalized)
     * - Time of day (encoded)
     * - Days since last transaction
     * - Transaction count in last hour
     * - Distance from home location
     * - etc.
     *
     * Example:
     *     {"features": [0.5, -1.2, 3.4, 0.0, 1.8, ...]}
     */
    FraudRequest: {
      /** Features */
      features: number[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IngestRequest */
    IngestRequest: {
      /** Filename */
      filename?: string | null;
      /** Content */
      content?: string | null;
    };
    /** RAGQuery */
    RAGQuery: {
      /** Query */
      query: string;
      /**
       * Top K
       * @default 3
       */
      top_k?: number | null;
    };
    /** RecommendRequest */
    RecommendRequest: {
      /** User Id */
      user_id?: string | number | null;
      /**
       * Top K
       * @default 5
       */
      top_k?: number | null;
      /** Movie Id */
      movie_id?: number | null;
      /** Features */
      features?: number[] | null;
      /** Candidate Ids */
      candidate_ids?: number[] | null;
    };
    /** RiskPayload */
    RiskPayload: {
      /**
       * Login Country
       * @default US
       */
      login_country?: string;
      /**
       * Device Known
       * @default true
       */
      device_known?: boolean;
      /**
       * Login Time
       * @description Hour of day in 0-23
       * @default 12
       */
      login_time?: number;
      /**
       * Clicks Per Minute
       * @default 10
       */
      clicks_per_minute?: number;
      /**
       * Files Accessed
       * @default 0
       */
      files_accessed?: number;
      /**
       * Transaction Amount
       * @default 0
       */
      transaction_amount?: number;
    };
    /** RiskSummary */
    RiskSummary: {
      /** Total Events */
      total_events: number;
      /** Decision Counts */
      decision_counts: {
        [key: string]: number;
      };
      /** Avg Risks */
      avg_risks: {
        [key: string]: number;
      };
    };
    /** TTSPayload */
    TTSPayload: {
      /** Text */
      text: string;
    };
    /** TopNRequest */
    TopNRequest: {
      /** User Id */
      user_id: number;
      /** Candidate Ids */
      candidate_ids: number[];
      /**
       * Top K
       * @default 5
       */
      top_k?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VisionRequest */
    VisionRequest: {
      /**
       * Dataset Dir
       * @description Relative path to an image classification dataset organized in class folders.
       * @default data/raw/vision/datasets/puneet6060/intel-image-classification/versions/2/seg_train/seg_train
       */
      dataset_dir?: string;
      /**
       * Run Experiment
       * @description Set to true to train a quick vision experiment using TensorFlow (may take longer).
       * @default false
       */
      run_experiment?: boolean;
      /**
       * Image Size
       * @description Height/width to resize images to.
       * @default 128
       */
      image_size?: number;
      /**
       * Batch Size
       * @description Batch size used during training when running experiments.
       * @default 32
       */
      batch_size?: number;
      /**
       * Epochs
       * @description Number of epochs when running the optional experiment.
       * @default 1
       */
      epochs?: number;
      /**
       * Validation Split
       * @description Validation split used when running the optional experiment.
       * @default 0.2
       */
      validation_split?: number;
      /**
       * Backbone
       * @description Backbone model for the optional experiment.
       * @default simple_cnn
       */
      backbone?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Chat */
  chat_api_chat_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Chat Multimodal
   * @description Single request: optional audio/image/video + message -> routed response + meta.
   *
   * This endpoint runs in-process inference for voice/vision and attaches results to `meta`.
   */
  chat_multimodal_api_chat_multimodal_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_chat_multimodal_api_chat_multimodal_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Chat Stream
   * @description SSE-style streaming endpoint.
   *
   * If OPENAI_API_KEY is set, streams LLM tokens from OpenAI.
   * Otherwise, falls back to word-chunk streaming of orchestrator reply.
   */
  chat_stream_api_chat_stream_get: {
    parameters: {
      query: {
        message: string;
        token?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Rag Query
   * @description Return top passages from local docs (data/docs).
   */
  rag_query_api_rag_query_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RAGQuery"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Recommend */
  recommend_api_recommend_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Explain */
  explain_api_recommend_explain_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExplainRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Recommend Multimodal
   * @description CLIP + FAISS multimodal recommender (additive).
   *
   * Provide either a text query, an uploaded image, or image_url/image_base64. If the index isn't built yet,
   * this endpoint returns 503 with instructions.
   */
  recommend_multimodal_api_recommend_multimodal_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_recommend_multimodal_api_recommend_multimodal_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Recommend Clothes
   * @description Image/text clothing recommendations (offline-first).
   *
   * Uses CLIP image tags when available; falls back to text-only matching.
   */
  recommend_clothes_api_recommend_clothes_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_recommend_clothes_api_recommend_clothes_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Recommend Topn */
  recommend_topn_api_recommend_topn_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopNRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Predict Behavior */
  predict_behavior_api_behavior_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BehaviorRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Predict Behavior Logs
   * @description Upload a behavior log CSV and return per-user anomaly scores (best-effort).
   */
  predict_behavior_logs_api_behavior_logs_post: {
    parameters: {
      query?: {
        max_rows?: number;
        top_n?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_predict_behavior_logs_api_behavior_logs_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Predict Fraud
   * @description Predict fraud probability for a transaction.
   *
   * This endpoint:
   * 1. Loads the fraud model (if not already loaded)
   * 2. Prepares input features in the correct format
   * 3. Runs model inference
   * 4. Returns fraud probability score
   *
   * Args:
   *     req: FraudRequest containing list of feature values
   *
   * Returns:
   *     dict: {
   *         "score": float,           # Fraud probability 0.0 to 1.0
   *         "input_features": int,    # Number of features provided
   *         "expected_features": int, # Number model expects
   *         "feature_names": list     # Names of features (if known)
   *     }
   *
   * Raises:
   *     HTTPException 503: If model is not available
   *     HTTPException 500: If inference fails
   *
   * Example usage with curl:
   *     curl -X POST http://localhost:8000/api/fraud \
   *          -H "Content-Type: application/json" \
   *          -d '{"features": [0.5, -1.2, 3.4, 0.0, 1.8]}'
   */
  predict_fraud_api_fraud_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FraudRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Predict Cyber */
  predict_cyber_api_cyber_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CyberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Vision Experiment */
  vision_experiment_api_vision_train_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Vision Predict
   * @description Predict class label for an uploaded image or image_url using the trained ResNet artifact.
   */
  vision_predict_api_vision_predict_post: {
    parameters: {
      query?: {
        top_k?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_vision_predict_api_vision_predict_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Face Emotion Predict
   * @description Predict a 7-class facial emotion label from an uploaded image.
   */
  face_emotion_predict_api_vision_face_emotion_predict_post: {
    parameters: {
      query?: {
        top_k?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_face_emotion_predict_api_vision_face_emotion_predict_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Vision Video Predict
   * @description Predict for an uploaded video by sampling frames, aggregating probabilities, and scoring temporal-consistency.
   *
   * If `models/vision/video_temporal_model.pkl` exists, also returns a learned temporal confidence score
   * via `temporal_confidence_model`.
   */
  vision_video_predict_api_vision_video_predict_post: {
    parameters: {
      query?: {
        fps?: number;
        max_frames?: number;
        top_k?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_vision_video_predict_api_vision_video_predict_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health Check
   * @description Quick health check endpoint.
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * Liveness Check
   * @description Kubernetes liveness probe.
   */
  liveness_check_health_live_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * Readiness Check
   * @description Kubernetes readiness probe with component checks.
   */
  readiness_check_health_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Detailed Health Check
   * @description Detailed health check with all components.
   */
  detailed_health_check_health_detailed_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Prometheus Metrics
   * @description Prometheus metrics endpoint.
   */
  prometheus_metrics_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Ready
   * @description Simple ready check for load balancers.
   */
  ready_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Risk Analyze */
  risk_analyze_api_risk_analyze_post: {
    parameters: {
      query?: {
        explain?: boolean;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RiskPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Log Event */
  log_event_api_monitor_log_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FraudLogEvent"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Summary */
  summary_api_monitor_summary_get: {
    parameters: {
      query?: {
        window_n?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Drift */
  drift_api_monitor_drift_get: {
    parameters: {
      query?: {
        window_n?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DriftReport"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Risk Summary */
  risk_summary_api_monitor_risk_summary_get: {
    parameters: {
      query?: {
        window_n?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Events
   * @description Return last N raw monitoring events (demo/debug).
   *
   * kind:
   *   - "risk"  -> `data/monitoring/logs/risk_events.jsonl`
   *   - "fraud" -> `data/monitoring/logs/fraud_events.jsonl`
   */
  events_api_monitor_events_get: {
    parameters: {
      query?: {
        kind?: string;
        window_n?: number;
      };
      header?: {
        authorization?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Build Baseline */
  build_baseline_api_monitor_baseline_build_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BaselineRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Voice Emotion */
  voice_emotion_api_voice_emotion_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_voice_emotion_api_voice_emotion_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Ingest Docs */
  ingest_docs_api_rag_ingest_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Upload Doc
   * @description Upload a .txt/.md doc into `data/docs/` and rebuild the local RAG index.
   */
  upload_doc_api_rag_upload_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_doc_api_rag_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Ask */
  ask_api_dsa_rag_ask_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Ingest Docs */
  ingest_docs_api_dsa_rag_ingest_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload Doc */
  upload_doc_api_dsa_rag_upload_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_doc_api_dsa_rag_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Predict Brand
   * @description Predict brand logos from an uploaded image or remote payload.
   *
   * Returns a list of detections: {brand, confidence, bbox:[x1,y1,x2,y2]}.
   */
  predict_brand_api_vision_brand_predict_post: {
    parameters: {
      query?: {
        conf?: number;
        kind?: string;
      };
      header?: {
        authorization?: string | null;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_predict_brand_api_vision_brand_predict_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Transcribe Audio */
  transcribe_audio_api_stt_transcribe_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_transcribe_audio_api_stt_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Tts Speak */
  tts_speak_api_tts_speak_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TTSPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Predict */
  predict_api_vision_video_temporal_predict_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_predict_api_vision_video_temporal_predict_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Api Health
   * @description Health check endpoint that returns system status and capabilities.
   *
   * Used by:
   * - Monitoring systems (Kubernetes, Docker health checks)
   * - Frontend to display system status
   * - DevOps to verify deployment
   *
   * Returns:
   *     dict: System status including:
   *         - status: "ok" if healthy
   *         - service: Service name
   *         - version: API version
   *         - python: Python version info
   *         - platform: OS information
   *         - optional_features: Available ML capabilities
   *
   * Example response:
   *     {
   *         "status": "ok",
   *         "service": "omnichatx",
   *         "version": "0.2",
   *         "python": {"version": "3.11.0", "implementation": "CPython"},
   *         "platform": {"system": "Darwin", "release": "23.0.0", "machine": "arm64"},
   *         "optional_features": {
   *             "webrtc": true,
   *             "stt": true,
   *             "clip": false,
   *             "faiss": true
   *         }
   *     }
   */
  api_health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Root Redirect
   * @description Root endpoint - Redirects to the UI or returns API info.
   *
   * Behavior:
   * - If UI is built: Redirects to /ui/ (React frontend)
   * - If UI not built: Returns a simple JSON message
   */
  root_redirect__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
