artifact_uri: /Users/pratik_n/Desktop/MyComputer/Sentifargo/runs/mlflow/690575434915126183/b2595831450845948accbe232e1c675e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '690575434915126183'
lifecycle_stage: active
run_id: b2595831450845948accbe232e1c675e
run_name: brand_prod
source_name: ''
source_type: 4
source_version: ''
start_time: 1765999741731
status: 1
tags: []
user_id: pratik_n
