artifact_uri: /Users/pratik_n/Desktop/MyComputer/universal-anomaly-intelligence-v2/runs/mlflow/716084780746542089/3d7e61729cd447e0bbd1ea030d3b0966/artifacts
end_time: null
entry_point_name: ''
experiment_id: '716084780746542089'
lifecycle_stage: active
run_id: 3d7e61729cd447e0bbd1ea030d3b0966
run_name: train2
source_name: ''
source_type: 4
source_version: ''
start_time: 1765996177812
status: 1
tags: []
user_id: pratik_n
