artifact_location: /Users/pratik_n/Desktop/MyComputer/universal-anomaly-intelligence-v2/runs/mlflow/716084780746542089
creation_time: 1765996111135
experiment_id: '716084780746542089'
last_update_time: 1765996111135
lifecycle_stage: active
name: /Shared/Ultralytics
